name: test
on:
  push:
    branches:
      - main

  pull_request:
  schedule:
    - cron: "0 0 * * 6" # At 00:00 on Saturday

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
